---

- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install git on all servers
    yum: name=git state=present

- hosts: ec2
  become: yes
  become_method: sudo

  roles:
    - rproxy

- hosts: ec2
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.nodejs

- hosts: ec2
  roles:
    - application
