---

- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install git on all servers
    yum: name=git state=present

- hosts: ec2
  become: yes
  become_method: sudo

  roles:
    - rproxy
